image: 
  name: ${DOCKER_REPO}/softwareplumbers/react-node-centos:0.0.7
  entrypoint: ["/bin/bash", "-l", "-c"]
  
stages:
  - init
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

login:
  stage: init
  script:
    - npm-cli-login

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script: npm test
  
publish:
  stage: deploy
  only: 
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    - npm version from-git
    - npm publish
   