image: 
  name: ${DOCKER_REPO}/softwareplumbers/react-node-centos:0.0.7
  entrypoint: ["/bin/bash", "-l", "-c"]
  
stages:
  - init
  - build
  - test

cache:
  paths:
    - node_modules/
    - ~/.npmrc

login:
  stage: init
  script:
    - npm-cli-login

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test