image: 
  name: ${DOCKER_REPO}/softwareplumbers/react-node-centos:0.0.7
  entrypoint: ["/bin/bash", "-l", "-c"]
  
stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - .npmrc

login:
  stage: init
  script:
    - npm set registry https://nexus.softwareplumbers.com/repository/npmjs-public/  
    - npm-cli-login path="." -r https://nexus.softwareplumbers.com/repository/npmjs-public/
    - npm-cli-login path="."
    - cat .npmrc

install_dependencies:
  stage: build
  script:
    - cat .npmrc
    - npm install

testing:
  stage: test
  script: 
    - npm test
  
publish:
  stage: deploy
  only: 
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    - cat $HOME/.npmrc
    - npm version --no-git-tag-version ${CI_COMMIT_REF_NAME} 
    - npm publish
   